### PR TITLE
deepspeech team progress

### PR DESCRIPTION
**Pull request by mohandodda0**

### CODE REVIEW

**Comment by jiashenC** [comment]
Nice doc 💯💯

**Comment by mohandodda0** [comment]
It is not updated as a link to a CSV file and other small items are needed. Another pull request would be needed.

**Comment by jiashenC** [comment]
Sure, I will update the structure little bit. Can you pull from `master` again and apply your changes?

**Comment by mohandodda0** [comment]
Yeah that works!

**Pull request merged**
